eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${custom.eureka.host}:${custom.eureka.port}/eureka
spring:
  application:
    name: eureka-server-1
  profiles: eureka-1
server:
  port: 8761
custom:
  eureka:
    port: 8761
    host: localhost
